#!/usr/bin/env python3
"""
Configure Neo4j connection for LegalNexus
This will save your Neo4j credentials for all scripts to use
"""
import os
import sys

def configure_neo4j():
    """Interactive configuration for Neo4j credentials"""
    
    print("\n" + "="*80)
    print("NEO4J CONFIGURATION")
    print("="*80)
    print("\nThis will configure your Neo4j Aura connection.")
    print("Make sure you have created a Neo4j Aura Free instance first.")
    print("\nGet your instance at: https://neo4j.com/cloud/platform/aura-graph-database/")
    print("="*80 + "\n")
    
    # Get credentials
    uri = input("Enter your Neo4j URI (e.g., neo4j+s://xxxxx.databases.neo4j.io): ").strip()
    username = input("Enter username (default: neo4j): ").strip() or "neo4j"
    password = input("Enter password: ").strip()
    
    if not uri or not password:
        print("\n❌ Error: URI and password are required!")
        return False
    
    # Test connection
    print("\n🔍 Testing connection...")
    try:
        from langchain_neo4j import Neo4jGraph
        
        graph = Neo4jGraph(
            url=uri,
            username=username,
            password=password
        )
        
        # Try a simple query
        result = graph.query("RETURN 'Connection successful' as message")
        print("✅ Connection successful!")
        
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        retry = input("\nWould you like to try again? (yes/no): ").strip().lower()
        if retry in ['yes', 'y']:
            return configure_neo4j()
        return False
    
    # Save to environment file format
    env_content = f"""# Neo4j Configuration for LegalNexus
# Generated by configure_neo4j.py

NEO4J_URI={uri}
NEO4J_USERNAME={username}
NEO4J_PASSWORD={password}

# Google API Key (already configured)
GOOGLE_API_KEY=AIzaSyA0dLTfkzxcZYP6KidlFClAyMLl6mea1y8
"""
    
    # Save to .env.neo4j (since .env is in gitignore)
    env_file = os.path.join(os.path.dirname(__file__), '.env.neo4j')
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ Configuration saved to: {env_file}")
    
    # Also save to shell export format for easy sourcing
    export_content = f"""# Source this file to set Neo4j environment variables
# Usage: source neo4j_env.sh

export NEO4J_URI="{uri}"
export NEO4J_USERNAME="{username}"
export NEO4J_PASSWORD="{password}"
export GOOGLE_API_KEY="AIzaSyA0dLTfkzxcZYP6KidlFClAyMLl6mea1y8"

echo "✓ Neo4j environment variables loaded"
"""
    
    shell_file = os.path.join(os.path.dirname(__file__), 'neo4j_env.sh')
    with open(shell_file, 'w') as f:
        f.write(export_content)
    
    print(f"✅ Shell config saved to: {shell_file}")
    
    print("\n" + "="*80)
    print("CONFIGURATION COMPLETE!")
    print("="*80)
    print("\nTo use these credentials:")
    print(f"  1. Run: source neo4j_env.sh")
    print(f"  2. Then run any script like: python3 load_complete_dataset.py")
    print("\nOr the scripts will automatically read from .env.neo4j")
    print("="*80 + "\n")
    
    return True

if __name__ == "__main__":
    success = configure_neo4j()
    sys.exit(0 if success else 1)

